#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Tr3umPHantDesigns.Resource", IsApplication=true)]

namespace Tr3umPHantDesigns
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bacground_request = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_contact = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int contact_round_input = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int flyer_gifts = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int flyer_mod = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_time = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int illustration_arizona = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Item = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int logo_bi = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int request_round_input = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int round_button = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int about_button = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int contact_button = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int designDate = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int email = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int firstName = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int full_image_view = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int graphic_button = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int gridview = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int information = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int lastName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int phoneNumber = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int request_button = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int spinner = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int submit_button = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int text1 = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Contact = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FullImage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Graphic = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GridViewLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Request = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
